FROM nginx:latest

# Copy custom nginx configuration
COPY nginx/docker-nginx.conf /etc/nginx/nginx.conf
COPY nginx/docker-site1.conf /etc/nginx/conf.d/site1.conf
COPY nginx/docker-site2.conf /etc/nginx/conf.d/site2.conf

# Create log directory
RUN mkdir -p /var/log/nginx

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
